webtalk_init -webtalk_dir C:/stapril/atom_computing/arp_handler/atom-fpga-april/arp_handler/arp.sim/sim_1/behav/xsim/xsim.dir/arp_handler_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Apr 11 23:20:45 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211479791_174119315_175670997_527" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1874b0f2-8480-46f6-833e-9f33d4f54fdf" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d4b572d30f294c4c96cd0df2757be016" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "432" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2904 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "68.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key SystemVerilog -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key File_Counter -value "22" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "277 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "70 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "1715" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "212" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "3.80_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "117200_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3211277596 -regid "211479791_174119315_175670997_527" -xml C:/stapril/atom_computing/arp_handler/atom-fpga-april/arp_handler/arp.sim/sim_1/behav/xsim/xsim.dir/arp_handler_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/stapril/atom_computing/arp_handler/atom-fpga-april/arp_handler/arp.sim/sim_1/behav/xsim/xsim.dir/arp_handler_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/stapril/atom_computing/arp_handler/atom-fpga-april/arp_handler/arp.sim/sim_1/behav/xsim/xsim.dir/arp_handler_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
