# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/stapril/hardware/atom/test/atom-fpga-april/ip/output_fifo/output_fifo/output_fifo.xci
# IP: The module: 'output_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/stapril/hardware/atom/test/atom-fpga-april/ip/output_fifo/output_fifo/output_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'output_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/stapril/hardware/atom/test/atom-fpga-april/ip/output_fifo/output_fifo/output_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'output_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/stapril/hardware/atom/test/atom-fpga-april/ip/output_fifo/output_fifo/output_fifo.xci
# IP: The module: 'output_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/stapril/hardware/atom/test/atom-fpga-april/ip/output_fifo/output_fifo/output_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'output_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/stapril/hardware/atom/test/atom-fpga-april/ip/output_fifo/output_fifo/output_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'output_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
